### ISSUE TITLE
Build a desktop app

### ISSUE THREAD

**Issue by sohaibafifi** [sohaibafifi/vrptw-instance-viewer#6]
Using electron\* or Qwebkit ? 
- https://github.com/atom/electron/

**Comment by LI-YIran** [comment]
Just to make sure: the solution file should be uploaded; but the instance file? Il will be stocked in server or also uploaded by user?
Thank you :)

**Comment by sohaibafifi** [comment]
Both files should be uploaded. The solution one is optional.

**Comment by LI-YIran** [comment]
Do we have to seperate the frontend and backend of our single PHP file as it is not supported in Electron? Looking forward to your advice.

**Comment by LI-YIran** [comment]
It's done

**Comment by sohaibafifi** [comment]
How ? 
Can you push please ?

**Comment by LI-YIran** [comment]
I just push it with my branche

2015-05-14 18:45 GMT+02:00 Sohaib Afifi notifications@github.com:

**Comment by LI-YIran** [comment]
I have send you un pull request

2015-05-14 22:14 GMT+02:00 Yiran LI yiran.li.1992@gmail.com:

**Comment by LI-YIran** [comment]
The ficher .html has not been updated. Last week I sent you another pull request with correction
